# Cadence UAT Environment Configuration
# Chart: cadence-0.24.2 (App: v0.24.0)

server:
  image:
    repository: ubercadence/server
    tag: "0.24.0"
    pullPolicy: IfNotPresent

  replicaCount: 1

  serviceAccount:
    create: true
    name: cadence
    annotations:
      iam.gke.io/gcp-service-account: "cadence-sa@focal-psyche-460009-a5.iam.gserviceaccount.com"

  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi

  config:
    persistence:
      default:
        driver: "sql"
        sql:
          pluginName: "mysql"
          host: "10.3.65.5"
          port: 3306
          database: "cadence1"
          user: "cadence"
          existingSecret: "cadence-mysql"

      visibility:
        driver: "sql"
        sql:
          pluginName: "mysql"
          host: "10.3.65.5"
          port: 3306
          database: "cadence_visibility1"
          user: "cadence"
          existingSecret: "cadence-mysql"

web:
  enabled: true
  replicaCount: 1
  image:
    repository: ubercadence/web
    tag: "3.30.2"
    pullPolicy: IfNotPresent

schema:
  setup:
    enabled: true
    backoffLimit: 100
  update:
    enabled: true
    backoffLimit: 100

mysql:
  enabled: false

cassandra:
  enabled: false
