# Cadence UAT - Minimal Resource Configuration

server:
  replicaCount: 1

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

  config:
    persistence:
      default:
        driver: "sql"
        sql:
          pluginName: "mysql"
          host: "10.3.65.5"
          port: 3306
          database: "cadence1"
          user: "cadence"
          existingSecret: "cadence-mysql"

      visibility:
        driver: "sql"
        sql:
          pluginName: "mysql"
          host: "10.3.65.5"
          port: 3306
          database: "cadence_visibility1"
          user: "cadence"
          existingSecret: "cadence-mysql"

web:
  enabled: true
  replicaCount: 1

schema:
  setup:
    enabled: false  # Databases cadence1 and cadence_visibility1 already initialized
  update:
    enabled: true
    backoffLimit: 100

mysql:
  enabled: false

cassandra:
  enabled: false
