# UAT Environment Configuration for Cadence
# Using official Cadence Helm chart v0.24.2

# Server configuration
server:
  image:
    repository: ubercadence/server
    tag: "0.24.0"
    pullPolicy: IfNotPresent

  replicaCount: 1  # Single replica for all services in UAT

  # Service Account with Workload Identity
  serviceAccount:
    create: true
    name: cadence
    annotations:
      iam.gke.io/gcp-service-account: "cadence-sa@focal-psyche-460009-a5.iam.gserviceaccount.com"

  # Resource limits
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi

  # Persistence configuration - MySQL
  config:
    persistence:
      default:
        driver: "sql"
        sql:
          pluginName: "mysql"
          host: "10.3.65.5"
          port: 3306
          database: "cadence"
          user: "cadence"
          existingSecret: "cadence-mysql"
          maxConns: 20
          maxIdleConns: 20
          maxConnLifetime: "1h"

      visibility:
        driver: "sql"
        sql:
          pluginName: "mysql"
          host: "10.3.65.5"
          port: 3306
          database: "cadence_visibility"
          user: "cadence"
          existingSecret: "cadence-mysql"
          maxConns: 10
          maxIdleConns: 10
          maxConnLifetime: "1h"

# Web UI configuration
web:
  enabled: true
  replicaCount: 1

  image:
    repository: ubercadence/web
    tag: "3.30.2"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8088

# Schema management
schema:
  setup:
    enabled: true
    backoffLimit: 10
  update:
    enabled: true
    backoffLimit: 10

# Disable built-in MySQL (using external Cloud SQL)
mysql:
  enabled: false

# Disable Cassandra
cassandra:
  enabled: false

# Enable Prometheus metrics
prometheus:
  enabled: false

# Node scheduling - allow History on cadence node pool
nodeSelector: {}

tolerations:
  - key: "workload"
    operator: "Equal"
    value: "cadence"
    effect: "NoSchedule"
