apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dailytumour-uat
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dailytumour-uat
  
  source:
    repoURL: https://github.com/your-org/dailytumour-uat-infrastructure.git
    targetRevision: main
    path: argocd-deploy/apps
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m