{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cadence.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cadence.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
    {{- with .Values.frontend.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "cadence.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.frontend.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "cadence.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
        {{- with .Values.frontend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "cadence.serviceAccountName" . }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        env:
        - name: SERVICES
          value: frontend
        - name: LOG_LEVEL
          value: {{ .Values.cadence.logLevel }}
        - name: DYNAMIC_CONFIG_FILE_PATH
          value: config/dynamicconfig/config.yaml
        - name: MYSQL_PWD
          valueFrom:
            secretKeyRef:
              name: {{ include "cadence.mysql.secretName" . }}
              key: {{ .Values.mysql.secretKeys.password }}
        - name: DB
          value: mysql
        - name: DB_PORT
          value: {{ include "cadence.mysql.port" . | quote }}
        - name: MYSQL_USER
          value: {{ include "cadence.mysql.user" . }}
        - name: MYSQL_SEEDS
          value: {{ include "cadence.mysql.host" . }}
        - name: KEYSPACE
          value: {{ include "cadence.mysql.database" . }}
        - name: VISIBILITY_KEYSPACE
          value: {{ include "cadence.mysql.visibilityDatabase" . }}
        - name: CASSANDRA_CONSISTENCY
          value: One
        - name: CASSANDRA_PROTO_VERSION
          value: "4"
        - name: PROMETHEUS_ENDPOINT
          value: 0.0.0.0:{{ .Values.prometheus.port }}
        ports:
        - name: rpc
          containerPort: 7933
          protocol: TCP
        - name: metrics
          containerPort: {{ .Values.prometheus.port }}
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: rpc
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: rpc
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          {{- toYaml .Values.frontend.resources | nindent 12 }}
        volumeMounts:
        - name: config
          mountPath: /etc/cadence/config/config.yaml
          subPath: config.yaml
        - name: dynamicconfig
          mountPath: /etc/cadence/config/dynamicconfig
      volumes:
      - name: config
        configMap:
          name: {{ include "cadence.fullname" . }}-config
      - name: dynamicconfig
        emptyDir: {}
{{- end }}
