{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cadence.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cadence.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
  - name: http
    port: {{ .Values.web.service.port }}
    targetPort: http
    protocol: TCP
  selector:
    {{- include "cadence.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
{{- end }}
