{{- if .Values.serviceAccount.create -}}
# Kubernetes ServiceAccount for Cadence pods
# This ServiceAccount is used by all Cadence components
# In GKE with Workload Identity, it's annotated to bind to a GCP service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cadence.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cadence.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    # Workload Identity annotation binds this K8s SA to GCP SA
    # Example: iam.gke.io/gcp-service-account: my-gcp-sa@project.iam.gserviceaccount.com
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
