apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cadence-mysql
  namespace: cadence-uat
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm-cluster-store

  target:
    name: cadence-mysql
    creationPolicy: Owner

  data:
    - secretKey: password
      remoteRef:
        key: dailytumour-uat-db-mysql-cadence-password
