apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cadence-mysql
  namespace: cadence
  labels:
    argocd.argoproj.io/instance: app-secrets
    app: cadence
    component: database
    environment: uat
spec:
  refreshInterval: 1m
  
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm-cluster-store
  
  target:
    name: cadence-mysql
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        labels:
          app: cadence
          component: database
      data:
        # Basic credentials
        password: "{{ .password | toString }}"
        user: "cadence"
        host: "10.3.65.5"
        port: "3306"
        
        # Environment variables for Cadence Helm chart
        MYSQL_PWD: "{{ .password | toString }}"
        MYSQL_USER: "cadence"
        MYSQL_SEEDS: "10.3.65.5"
        DB: "mysql"
        DB_PORT: "3306"
        PERSISTENCE_DRIVER: "sql"
        
        # Database names
        KEYSPACE: "cadence"
        VISIBILITY_KEYSPACE: "cadence_visibility"

        # Full connection strings (DSN format)
        CADENCE_STORE_DSN: "cadence:{{ .password | toString }}@tcp(10.3.65.5:3306)/cadence?parseTime=true&clientFoundRows=true&multiStatements=true"
        CADENCE_VISIBILITY_STORE_DSN: "cadence:{{ .password | toString }}@tcp(10.3.65.5:3306)/cadence_visibility?parseTime=true&clientFoundRows=true&multiStatements=true"
  
  data:
    - secretKey: password
      remoteRef:
        key: dailytumour-uat-db-mysql-cadence-password
        conversionStrategy: Default
        decodingStrategy: None